version: '3.8'

services:
  registry:
    image: registry:latest
    volumes:
    - ./docker/registry:/var/lib/registry
    networks:
    - game
  user:
    build:
      context: ./.docker/user
      dockerfile: dockerfile
    image: alpine:latest
    container_name: user
    entrypoint: sleep infinity
    networks:
    - game

networks:
  game:
    driver: bridge