version: '3.8'

services:
  registry:
    image: registry:latest
    volumes:
    - ./.docker/registry/cache:/cache
    - ./.docker/registry/config.yml:/etc/docker/registry/config.yml
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /cache
    networks:
    - game
  user:
    build:
      context: ./.docker/user
      dockerfile: dockerfile
    image: alpine:latest
    container_name: user
    entrypoint: sleep infinity
    networks:
    - game

networks:
  game:
    driver: bridge