version: '3.8'

services:
  checker:
    build:
      context: ${SERVICE_NAME}
      dockerfile: .docker/Dockerfile
      args:
        - SERVICE_NAME=${SERVICE_NAME}
    container_name: ${HOSTNAME}
    hostname: ${HOSTNAME}
    privileged: true
    restart: always
    stop_signal: SIGINT
    working_dir: /checker
    environment:
      - GATEWAY_IPV4=${GATEWAY_IPV4}
      - GATEWAY_IPV6=${GATEWAY_IPV6}
      - HOSTNAME=${HOSTNAME}
      - SERVICE_ID=${SERVICE_ID}
      - SERVICE_NAME=${SERVICE_NAME}
      - TICK_SECONDS=${TICK_SECONDS}
    networks:
     range_checker:
        ipv4_address: ${IPV4}
        ipv6_address: ${IPV6}


networks:
  range_checker:
    driver: bridge
    external: true