services:
  checker:
    build:
      context: ${SERVICE_NAME}
      dockerfile: .docker/Dockerfile
      args:
        - SERVICE_NAME=${SERVICE_NAME}
    container_name: ${HOSTNAME}
    hostname: ${HOSTNAME}
    privileged: true
    restart: always
    stop_signal: SIGINT
    working_dir: /checker
    environment:
      - GATEWAY=${GATEWAY}
      - HOSTNAME=${HOSTNAME}
      - SERVICE_ID=${SERVICE_ID}
      - SERVICE_NAME=${SERVICE_NAME}
      - TICK_SECONDS=${TICK_SECONDS}
    networks:
      glitch_checker:
        ipv4_address: ${IP}

networks:
  glitch_checker:
    driver: bridge
    external: true
