version: '3.8'

services:
  host:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    privileged: true
    restart: always
    volumes:
    - ./${SERVICE_ID}:/service
    - ./.docker/entry.sh:/entry.sh
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - SERVICE_ID=${SERVICE_ID}
    working_dir: /service
    entrypoint: sh /entry.sh
    network_mode: host